baseURL = "http://localhost:1313"  # Will be overridden in production config
languageCode = "en-us"
title = "Your Portfolio"  # You can customize this

# Content Management
enableGitInfo = true  # For last modified dates
enableRobotsTXT = true  # For SEO
buildDrafts = false
buildFuture = false
buildExpired = false

# Performance
minify = true
disableKinds = ['taxonomy', 'term']  # We'll enable these later as needed

[markup]
  [markup.highlight]
    style = "dracula"  # Code highlighting style
    lineNos = true
  [markup.goldmark.renderer]
    unsafe = true  # Allows HTML in markdown

theme = "PaperMod"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[permalinks]
  [permalinks.taxonomies]
    category = "/categories/:slug/"
    tag = "/tags/:slug/"
    series = "/series/:slug/"

# Configure taxonomy terms pages
[taxonomyTerms]
  [taxonomyTerms.categories]
    title = "Categories"
    description = "Browse technical articles by category"
  [taxonomyTerms.tags]
    title = "Tags"
    description = "Browse content by tags"
  [taxonomyTerms.series]
    title = "Series"
    description = "Article series and learning journeys"