baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Veltalldev"
theme = "PaperMod"

[params]
  mainSections = ["professional", "personal"]
  math = true
# Profile mode configurations
[params.profileMode]
enabled = true
title = "Welcome to My Portfolio"
subtitle = "I build elegant solutions to complex problems, focusing on clean code and thoughtful system design. My portfolio showcases both professional work and personal interests, reflecting my journey in software development and technical writing."
imageUrl = "" # Add if you want a profile image
buttons = [
    { name = "Professional", url = "/professional" },
    { name = "Personal", url = "/personal" }
]

# Keep your social icons config
[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/veltalldev"

[[params.socialIcons]]
name = "YouTube"
url = "https://www.youtube.com/@vdinh143"

[[params.socialIcons]]
name = "BlueSky"
url = "https://bsky.app/profile/kafeaulait.bsky.social"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false  # Important! Use CSS classes instead of inline styles
    noHl = false
    style = 'monokai'  # You can pick a base style, but we'll override with CSS
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  
[outputs]
  home = ["HTML", "RSS", "JSON"]