baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Your Portfolio"
theme = "PaperMod"

# Core settings
enableGitInfo = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
minify = true

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Markup Configuration
[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = true
  [markup.goldmark.renderer]
    unsafe = true

# Basic theme parameters (only essential configs)
[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true