# Basic PaperMod configuration
[profileMode]
enabled = false  # Disable profile mode to use home info
title = "Test Title"
subtitle = "Testing PaperMod Setup"
imageUrl = ""
imageTitle = ""
buttons = [
    { name = "Posts", url = "posts" },
    { name = "Tags", url = "tags" }
]

[homeInfoParams]
Title = "Welcome to My Portfolio"
Content = "A journey through software engineering, problem-solving, and personal growth."

# Default sections to show on home
mainSections = ["professional", "personal"]

# Theme configuration
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true

