name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install postcss-cli autoprefixer @fullhuman/postcss-purgecss
          npm install html-validate
          npm install broken-link-checker -g
          npm install --save-dev @google/lighthouse

      - name: Validate HTML (on pull requests)
        if: github.event_name == 'pull_request'
        run: |
          hugo --minify
          html-validate public/**/*.html

      - name: Check for broken links (on pull requests)
        if: github.event_name == 'pull_request'
        run: blc https://veltalldev.github.io/portfolio -r --exclude-external

      - name: Build site
        run: |
          hugo --minify
          hugo deploy --force --maxDeletes -1
        env:
          HUGO_ENV: production
          HUGO_BASEURL: ${{ secrets.HUGO_BASEURL }}

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://veltalldev.github.io/portfolio/
            https://veltalldev.github.io/portfolio/professional/
            https://veltalldev.github.io/portfolio/personal/
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: './lighthouserc.json'

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public