name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.126.0'  # Updated to latest stable version
          extended: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install postcss-cli autoprefixer @fullhuman/postcss-purgecss
          npm install html-validate
          npm install broken-link-checker -g
          npm install lighthouse

      - name: Validate HTML
        if: github.event_name == 'pull_request'
        run: |
          hugo --minify
          html-validate public/**/*.html

      - name: Check for broken links
        if: github.event_name == 'pull_request'
        run: blc http://localhost:1313 -r --exclude-external

      - name: Build site
        run: |
          echo "Starting Hugo build..."
          hugo --minify
          echo "Build complete. Checking output..."
          ls -la public/
          cat public/index.html
        env:
          HUGO_ENV: production
          HUGO_BASEURL: ${{ secrets.HUGO_BASEURL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public